$axure.loadCurrentPage({
  "url":"文档说明.html",
  "generationDate":new Date(1449315205453.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"ff95a270827c41c7891483ebce9113c3",
    "type":"Axure:Page",
    "name":"文档说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3303ec88616544118136e781b6757d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":460,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297834dad38b488a8b9c5a8d23f77a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":460,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文档说明/u0.png"}},
{
          "id":"fb0527fef17448c8bd596c36b4e4f2ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":274},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0319ce1af9b3441c99cf4e20c36ab0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":274},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"918448284cbd4cb1b3d2ed739ecdac97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":54,
              "y":50},
            "size":{
              "width":295,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2283a0cf24c74d88b87fe9419fb0159e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":54,
                  "y":50},
                "size":{
                  "width":295,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdd5e3d5b5164c50a130b6901fb64f13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":54,
              "y":138},
            "size":{
              "width":406,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a5220365de84bcdadbb22339df10629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":54,
                  "y":138},
                "size":{
                  "width":406,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3303ec88616544118136e781b6757d12":{
      "scriptId":"u0"},
    "297834dad38b488a8b9c5a8d23f77a94":{
      "scriptId":"u1"},
    "fb0527fef17448c8bd596c36b4e4f2ee":{
      "scriptId":"u2"},
    "0319ce1af9b3441c99cf4e20c36ab0f3":{
      "scriptId":"u3"},
    "918448284cbd4cb1b3d2ed739ecdac97":{
      "scriptId":"u4"},
    "2283a0cf24c74d88b87fe9419fb0159e":{
      "scriptId":"u5"},
    "cdd5e3d5b5164c50a130b6901fb64f13":{
      "scriptId":"u6"},
    "0a5220365de84bcdadbb22339df10629":{
      "scriptId":"u7"}}});