$axure.loadCurrentPage({
  "url":"标签.html",
  "generationDate":new Date(1449315208442.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"01065997633b49839f906708d5d04611",
    "type":"Axure:Page",
    "name":"标签",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1<br> (If value of LabelState equals &quot;书签&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"LabelState"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"书签",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"Set 标签 to 书签",
                "panelsToStates":[{
                    "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":3,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "compress":false}}}]}]},
{
            "description":"Case 2<br> (Else If value of LabelState equals &quot;问答&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"LabelState"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"问答",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"Set 标签 to 问答",
                "panelsToStates":[{
                    "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":1,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "compress":false}}}]}]},
{
            "description":"Case 3<br> (Else If value of LabelState equals &quot;文章&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"LabelState"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"文章",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"Set 标签 to 文章",
                "panelsToStates":[{
                    "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"c7feff66a0044f8eae8d12988a1fe85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0031f42fb3f477a9a915f282f0d4790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"a937b6cbe3b44bc2b9412518b18d2dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":80},
            "size":{
              "width":748,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ef309a2f1b4ebeb22c33deac50cd52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":80},
                "size":{
                  "width":748,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6891228cbdb74e55bb19c45d33731d87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":170},
            "size":{
              "width":202,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9032d354c20541e990c9c9ea6c651e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":170},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签/u4.png"}},
{
          "id":"696e59019cbc4cb4b8fba52a338638f9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "location":{
              "x":25,
              "y":208},
            "size":{
              "width":747,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/标签/u6_line.png"}},
{
          "id":"860030681ae745818feaca746a40512f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":170},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 标签 to 问答",
                      "panelsToStates":[{
                          "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"92461a5c39e0434a9ab2fa04c344cf4e",
          "label":"标签",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":218},
            "size":{
              "width":748,
              "height":292}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f3583558f8724aa9bf6f6f3b350a1b31",
              "label":"问答",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8d97244675084b0799fc6ee9efda7827",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":11},
                    "size":{
                      "width":388,
                      "height":69}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f37bb3d8fda14170b57dc02216d513c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":11},
                        "size":{
                          "width":388,
                          "height":69}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u9.png"}},
{
                  "id":"a6bba55e3fa7458f970511a3659f72db",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":20},
                    "size":{
                      "width":40,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c5ae9c21886403fb1915fe60a7b1b29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":20},
                        "size":{
                          "width":40,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/问答社区/u21.png"}}]},
{
              "id":"7888f9fead974903b4de87fdbec9cd4b",
              "label":"文章",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f24a8119c236413f92926153124a1818",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":30},
                    "size":{
                      "width":587,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5469fee03b64a64998bdbdc64f7a0b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":30},
                        "size":{
                          "width":587,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u13.png"}},
{
                  "id":"fae9905c5d9746c3b815409b46340d2c",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCFF},
                    "location":{
                      "x":80,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1df3609efaa443708a5aacc153fef3a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCFF},
                        "location":{
                          "x":80,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/博客/u84.png"}},
{
                  "id":"60e56ac23b4444ca8e27a18caf150f8d",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":116,
                      "y":100},
                    "size":{
                      "width":64,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04af45d1132b47aa82b78a4b602b6f26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":116,
                          "y":100},
                        "size":{
                          "width":64,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"20d8bea72925425bab0aaa3b41ed0f93",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":371,
                      "y":42},
                    "size":{
                      "width":29,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4236f7710a64f27ad102ea4f3a05ed0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":371,
                          "y":42},
                        "size":{
                          "width":29,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/问答社区/u78.png"}}]},
{
              "id":"60d9242dae7d4861852e4e6ba935189d",
              "label":"书签",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"75718d0bb2d94fc38fb389a0140ed3b1",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":500,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e8c56148ebc4f8ab7200cae848a74ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":500,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u21.png"}},
{
                  "id":"90311eb7c61f447eb7f82fb0fe9283a9",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":49},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94788f13fedd4737b48032fce76e2375",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":49},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"558b536725a247849b17768001b4b355",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":21},
                    "size":{
                      "width":157,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"713e7a5561ef409da9e9b56f814daa88",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":21},
                        "size":{
                          "width":157,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d85929986ed749a396687d5ce0f0c4c1",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":36},
                    "size":{
                      "width":31,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc11eb608408447fbd62da7411f32019",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":36},
                        "size":{
                          "width":31,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u27.png"}},
{
                  "id":"c12238f1f3f04c838f5d8a85caa23b70",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":444,
                      "y":27},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23acdbe6c55946b98c891a1e7fe6d344",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":444,
                          "y":27},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71038e3437f04349a29f720f82a5eb95",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":444,
                      "y":53},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"92ae09a8087e412a8ec7c72686547b6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":444,
                          "y":53},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1b0b17552596418093f436fee9b9d395",
                  "label":"",
                  "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250.5,
                      "y":24},
                    "size":{
                      "width":39,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"984f0e3174674d69a8be236b2d7db31c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"92461a5c39e0434a9ab2fa04c344cf4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":250.5,
                          "y":24},
                        "size":{
                          "width":39,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 标签 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"标签.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/书签/u73.png"}}]}]},
{
          "id":"72636683dbe44f3b8bbde32a23707ac1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":170},
            "size":{
              "width":96,
              "height":38}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 标签 to 文章",
                      "panelsToStates":[{
                          "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"eb43bdc86a534a979b6d1338557a1902",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":186.5},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/添加书签/u63_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/博客/u66_line.png"}},
{
          "id":"c6080ec7b4794d30b60fd9365e5b7b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":184},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36a17a2c9c824081ac5ae1c45b85dc22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":184},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a509fe21ec3a4210b5e3a75fd1bf4d54",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"eed3bd32640d48d9be271d32454b43df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":175},
            "size":{
              "width":100,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1562fee8794402daa1176bfeb5df878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":175},
                "size":{
                  "width":100,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 标签 to 书签",
                      "panelsToStates":[{
                          "panelPath":["92461a5c39e0434a9ab2fa04c344cf4e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/标签/u75.png"}},
{
          "id":"6cd9ad23905d43c2a844c6b13547749d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":198},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/博客/u66_line.png"}},
{
          "id":"a939443a1b364248abcf5a347686ad2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":141},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe72edc9eb0946c2a35de67a0496dc47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1060,
                  "y":141},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65b2d76ac1e54e77babac923198bd968",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":70},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41d78b5486a4c878f69dce87d3f3f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":70},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/书签/u14.png"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "c7feff66a0044f8eae8d12988a1fe85e":{
      "scriptId":"u0"},
    "b0031f42fb3f477a9a915f282f0d4790":{
      "scriptId":"u1"},
    "a937b6cbe3b44bc2b9412518b18d2dd3":{
      "scriptId":"u2"},
    "b0ef309a2f1b4ebeb22c33deac50cd52":{
      "scriptId":"u3"},
    "6891228cbdb74e55bb19c45d33731d87":{
      "scriptId":"u4"},
    "9032d354c20541e990c9c9ea6c651e3b":{
      "scriptId":"u5"},
    "696e59019cbc4cb4b8fba52a338638f9":{
      "scriptId":"u6"},
    "860030681ae745818feaca746a40512f":{
      "scriptId":"u7"},
    "92461a5c39e0434a9ab2fa04c344cf4e":{
      "scriptId":"u8"},
    "8d97244675084b0799fc6ee9efda7827":{
      "scriptId":"u9"},
    "f37bb3d8fda14170b57dc02216d513c4":{
      "scriptId":"u10"},
    "a6bba55e3fa7458f970511a3659f72db":{
      "scriptId":"u11"},
    "2c5ae9c21886403fb1915fe60a7b1b29":{
      "scriptId":"u12"},
    "f24a8119c236413f92926153124a1818":{
      "scriptId":"u13"},
    "e5469fee03b64a64998bdbdc64f7a0b4":{
      "scriptId":"u14"},
    "fae9905c5d9746c3b815409b46340d2c":{
      "scriptId":"u15"},
    "1df3609efaa443708a5aacc153fef3a2":{
      "scriptId":"u16"},
    "60e56ac23b4444ca8e27a18caf150f8d":{
      "scriptId":"u17"},
    "04af45d1132b47aa82b78a4b602b6f26":{
      "scriptId":"u18"},
    "20d8bea72925425bab0aaa3b41ed0f93":{
      "scriptId":"u19"},
    "c4236f7710a64f27ad102ea4f3a05ed0":{
      "scriptId":"u20"},
    "75718d0bb2d94fc38fb389a0140ed3b1":{
      "scriptId":"u21"},
    "5e8c56148ebc4f8ab7200cae848a74ad":{
      "scriptId":"u22"},
    "90311eb7c61f447eb7f82fb0fe9283a9":{
      "scriptId":"u23"},
    "94788f13fedd4737b48032fce76e2375":{
      "scriptId":"u24"},
    "558b536725a247849b17768001b4b355":{
      "scriptId":"u25"},
    "713e7a5561ef409da9e9b56f814daa88":{
      "scriptId":"u26"},
    "d85929986ed749a396687d5ce0f0c4c1":{
      "scriptId":"u27"},
    "fc11eb608408447fbd62da7411f32019":{
      "scriptId":"u28"},
    "c12238f1f3f04c838f5d8a85caa23b70":{
      "scriptId":"u29"},
    "23acdbe6c55946b98c891a1e7fe6d344":{
      "scriptId":"u30"},
    "71038e3437f04349a29f720f82a5eb95":{
      "scriptId":"u31"},
    "92ae09a8087e412a8ec7c72686547b6e":{
      "scriptId":"u32"},
    "1b0b17552596418093f436fee9b9d395":{
      "scriptId":"u33"},
    "984f0e3174674d69a8be236b2d7db31c":{
      "scriptId":"u34"},
    "72636683dbe44f3b8bbde32a23707ac1":{
      "scriptId":"u35"},
    "eb43bdc86a534a979b6d1338557a1902":{
      "scriptId":"u36"},
    "c6080ec7b4794d30b60fd9365e5b7b29":{
      "scriptId":"u37"},
    "36a17a2c9c824081ac5ae1c45b85dc22":{
      "scriptId":"u38"},
    "a509fe21ec3a4210b5e3a75fd1bf4d54":{
      "scriptId":"u39",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u40"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u41"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u42"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u43"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u44"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u45"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u46"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u47"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u48"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u49"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u50"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u51"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u52"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u53"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u54"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u55"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u56"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u57"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u58"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u59"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u60"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u61"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u62"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u63"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u64"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u65"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u66"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u67"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u68"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u69"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u70"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u71"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u72"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u73"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u74"}},
    "eed3bd32640d48d9be271d32454b43df":{
      "scriptId":"u75"},
    "d1562fee8794402daa1176bfeb5df878":{
      "scriptId":"u76"},
    "6cd9ad23905d43c2a844c6b13547749d":{
      "scriptId":"u77"},
    "a939443a1b364248abcf5a347686ad2f":{
      "scriptId":"u78"},
    "fe72edc9eb0946c2a35de67a0496dc47":{
      "scriptId":"u79"},
    "65b2d76ac1e54e77babac923198bd968":{
      "scriptId":"u80"},
    "a41d78b5486a4c878f69dce87d3f3f67":{
      "scriptId":"u81"}}});