$axure.loadCurrentPage({
  "url":"d3实例.html",
  "generationDate":new Date(1449315205968.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"301929c313814ff8bb408e83e59fd21a",
    "type":"Axure:Page",
    "name":"D3实例",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2791b42f08ca4a4da10799c44eb653e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec5bccdcafbd41feb9e1eafb132456ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"1054bf990435410b8d4d444c22d327f4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"2fd8235ac0f045d58610c821414f9267",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":106},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55818327830546cfbe4fde4e711b05f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":106},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2791b42f08ca4a4da10799c44eb653e8":{
      "scriptId":"u0"},
    "ec5bccdcafbd41feb9e1eafb132456ac":{
      "scriptId":"u1"},
    "1054bf990435410b8d4d444c22d327f4":{
      "scriptId":"u2",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u3"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u4"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u5"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u6"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u7"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u8"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u9"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u10"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u11"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u12"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u13"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u14"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u15"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u16"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u17"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u18"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u19"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u20"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u21"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u22"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u23"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u24"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u25"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u26"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u27"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u28"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u29"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u30"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u31"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u32"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u33"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u34"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u35"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u36"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u37"}},
    "2fd8235ac0f045d58610c821414f9267":{
      "scriptId":"u38"},
    "55818327830546cfbe4fde4e711b05f8":{
      "scriptId":"u39"}}});