$axure.loadCurrentPage({
  "url":"d3中文网.html",
  "generationDate":new Date(1449315205036.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"0eda05156e3d4f1d83bb675feb63b287",
    "type":"Axure:Page",
    "name":"D3中文网",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"Show/Hide Widget",
                "objectsToFades":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"4b670e06e9204b598c682b0cb75388ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260.000061035156,
              "y":0},
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2981120812594622ae44d38646ae7a5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260.000061035156,
                  "y":0},
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"2696e346775545e2a5c9759df7bdd697",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260.000061035156,
              "y":60},
            "size":{
              "width":1000,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11bde14c15e7462a8686109fc6cbd62e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260.000061035156,
                  "y":60},
                "size":{
                  "width":1000,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u2.jpg"}},
{
          "id":"a48f1b88069e42ecb05ac12d90ecfc72",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":705.5,
              "y":170},
            "size":{
              "width":93,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c740c8169446488e178700a77dd40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":705.5,
                  "y":170},
                "size":{
                  "width":93,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2275a2677994494d9526d066044ea6aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":571.5,
              "y":269},
            "size":{
              "width":361,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63294cbfe1624ababee057e8e1965e36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":571.5,
                  "y":269},
                "size":{
                  "width":361,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71da2f334f894a73b98dd0445b06db4f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":624.000061035156,
              "y":345},
            "size":{
              "width":256,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8d10a49a394ac29c6b5602aab4b4ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":624.000061035156,
                  "y":345},
                "size":{
                  "width":256,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u8.png"}},
{
          "id":"582f00c527cb475386d648a4b129b6bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":260,
              "y":520},
            "size":{
              "width":1000,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7589f9e98c6c4679a3c5ec3b53b8bdd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":260,
                  "y":520},
                "size":{
                  "width":1000,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u10.png"}},
{
          "id":"a78183bd007a4bc9acd51f151f431ef0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":260.000061035156,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"a09185b32f8f4be19289ece2c3da5b8a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1270,
              "y":130},
            "size":{
              "width":100,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/d3中文网/u48_line.png"}},
{
          "id":"3f619e4c456f427791faaa0f8e7abdbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1370,
              "y":103},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92df1041835a4db89b49e625465256e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1370,
                  "y":103},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31cdd82b914c4fa796a679da81f55675",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":572,
              "y":537},
            "size":{
              "width":132,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c2b4b2a4144449a884c407f64471694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":572,
                  "y":537},
                "size":{
                  "width":132,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db2ede08d4954590909def9435d9eace",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":537},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b83279834d34cf4a5d485419c00edc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":537},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0d2c333f16f483b84a77ffc734cfc4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":590},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efee4b9988024b8798e20aef23e4f28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":590},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "4b670e06e9204b598c682b0cb75388ca":{
      "scriptId":"u0"},
    "2981120812594622ae44d38646ae7a5a":{
      "scriptId":"u1"},
    "2696e346775545e2a5c9759df7bdd697":{
      "scriptId":"u2"},
    "11bde14c15e7462a8686109fc6cbd62e":{
      "scriptId":"u3"},
    "a48f1b88069e42ecb05ac12d90ecfc72":{
      "scriptId":"u4"},
    "66c740c8169446488e178700a77dd40d":{
      "scriptId":"u5"},
    "2275a2677994494d9526d066044ea6aa":{
      "scriptId":"u6"},
    "63294cbfe1624ababee057e8e1965e36":{
      "scriptId":"u7"},
    "71da2f334f894a73b98dd0445b06db4f":{
      "scriptId":"u8"},
    "ed8d10a49a394ac29c6b5602aab4b4ba":{
      "scriptId":"u9"},
    "582f00c527cb475386d648a4b129b6bb":{
      "scriptId":"u10"},
    "7589f9e98c6c4679a3c5ec3b53b8bdd4":{
      "scriptId":"u11"},
    "a78183bd007a4bc9acd51f151f431ef0":{
      "scriptId":"u12",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u13"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u14"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u15"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u16"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u17"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u18"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u19"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u20"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u21"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u22"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u23"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u24"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u25"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u26"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u27"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u28"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u29"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u30"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u31"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u32"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u33"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u34"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u35"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u36"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u37"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u38"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u39"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u40"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u41"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u42"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u43"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u44"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u45"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u46"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u47"}},
    "a09185b32f8f4be19289ece2c3da5b8a":{
      "scriptId":"u48"},
    "3f619e4c456f427791faaa0f8e7abdbe":{
      "scriptId":"u49"},
    "92df1041835a4db89b49e625465256e1":{
      "scriptId":"u50"},
    "31cdd82b914c4fa796a679da81f55675":{
      "scriptId":"u51"},
    "0c2b4b2a4144449a884c407f64471694":{
      "scriptId":"u52"},
    "db2ede08d4954590909def9435d9eace":{
      "scriptId":"u53"},
    "7b83279834d34cf4a5d485419c00edc9":{
      "scriptId":"u54"},
    "d0d2c333f16f483b84a77ffc734cfc4f":{
      "scriptId":"u55"},
    "efee4b9988024b8798e20aef23e4f28d":{
      "scriptId":"u56"}}});