$axure.loadCurrentPage({
  "url":"我要写文章.html",
  "generationDate":new Date(1449315207888.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"c814ac112af7489ea0b556837f25b8bb",
    "type":"Axure:Page",
    "name":"我要写文章",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8bf36b87ee124dd1b8cbea2cf7c727ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e26effec0a549398861096595f35f82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"93b062737f314ad99474ba5019169d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Adobe 楷体 Std R', 'Adobe 楷体 Std'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":49,
              "y":0},
            "size":{
              "width":93,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cfb66bfcfe24207978ebec49abffef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 楷体 Std R', 'Adobe 楷体 Std'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":0},
                "size":{
                  "width":93,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94321285d1174f098872a56f357b0d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":423,
              "y":17},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48338c15146849569697456b185da929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":423,
                  "y":17},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ed1b93d4e9747e9a725dd46b1b655d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":17},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b2c17692f844f891374c146d01cdf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":17},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89fdf8591f1c43d799b1b033392058ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":26,
              "y":80},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f911a5b2a07f408d8199386063efb5ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":26,
                  "y":80},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711f2290f086408b92163c80bd107456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":130},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109688de2e13486cbd2da87fcb821ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":130},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e8d591e13f04c8898f1d199dec0ad9d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":160},
            "size":{
              "width":514,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"66fe63cadbc54bd89dce67fdf6071aed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03b0571c11f4020930a3554fcc29d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30efd29949944a289fcab4734b498037",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":250},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e4d74c0fe3da49eba868c41a8ea2ddfa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":310},
            "size":{
              "width":514,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbd2707ec25d4368b4fb6ff25d10538c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":310},
                "size":{
                  "width":514,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我要写文章/u16.png"}},
{
          "id":"9231b018978c4dd8b3b7a72e36b76bd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":640},
            "size":{
              "width":524,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b871682cce4c445ab301f87044bdfb29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":640},
                "size":{
                  "width":524,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我要写文章/u18.png"}},
{
          "id":"b64195519ad747d0bad181e410115baf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "location":{
              "x":570,
              "y":60},
            "size":{
              "width":10,
              "height":1230}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/问题详情/u17_line.png"}},
{
          "id":"378b922ac36e48cbae085ca4634a67f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":78},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14de0759d164dfdb4bc1954a84814b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":78},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68a90496e917462ab343a2668f90cadb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":960},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e6cbd7a25d340fabc042049ce0eb333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":960},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/书签/u14.png"}},
{
          "id":"eb83c3dd82f74d48b9c0463cd0c4113c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":960},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eb6b4859b8d47d688e1fe78b6e2e681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":960},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/书签/u14.png"}},
{
          "id":"465150bf6107491a93de0cc1b2f032ad",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"dfa53bc0d8f14f7b9feff7382dc808ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":227,
              "y":426},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6348f140319243c0b684e3448cfeacf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":426},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8bf36b87ee124dd1b8cbea2cf7c727ec":{
      "scriptId":"u0"},
    "9e26effec0a549398861096595f35f82":{
      "scriptId":"u1"},
    "93b062737f314ad99474ba5019169d01":{
      "scriptId":"u2"},
    "8cfb66bfcfe24207978ebec49abffef1":{
      "scriptId":"u3"},
    "94321285d1174f098872a56f357b0d92":{
      "scriptId":"u4"},
    "48338c15146849569697456b185da929":{
      "scriptId":"u5"},
    "8ed1b93d4e9747e9a725dd46b1b655d0":{
      "scriptId":"u6"},
    "a7b2c17692f844f891374c146d01cdf2":{
      "scriptId":"u7"},
    "89fdf8591f1c43d799b1b033392058ec":{
      "scriptId":"u8"},
    "f911a5b2a07f408d8199386063efb5ef":{
      "scriptId":"u9"},
    "711f2290f086408b92163c80bd107456":{
      "scriptId":"u10"},
    "109688de2e13486cbd2da87fcb821ee0":{
      "scriptId":"u11"},
    "0e8d591e13f04c8898f1d199dec0ad9d":{
      "scriptId":"u12"},
    "66fe63cadbc54bd89dce67fdf6071aed":{
      "scriptId":"u13"},
    "f03b0571c11f4020930a3554fcc29d7c":{
      "scriptId":"u14"},
    "30efd29949944a289fcab4734b498037":{
      "scriptId":"u15"},
    "e4d74c0fe3da49eba868c41a8ea2ddfa":{
      "scriptId":"u16"},
    "fbd2707ec25d4368b4fb6ff25d10538c":{
      "scriptId":"u17"},
    "9231b018978c4dd8b3b7a72e36b76bd7":{
      "scriptId":"u18"},
    "b871682cce4c445ab301f87044bdfb29":{
      "scriptId":"u19"},
    "b64195519ad747d0bad181e410115baf":{
      "scriptId":"u20"},
    "378b922ac36e48cbae085ca4634a67f3":{
      "scriptId":"u21"},
    "f14de0759d164dfdb4bc1954a84814b3":{
      "scriptId":"u22"},
    "68a90496e917462ab343a2668f90cadb":{
      "scriptId":"u23"},
    "1e6cbd7a25d340fabc042049ce0eb333":{
      "scriptId":"u24"},
    "eb83c3dd82f74d48b9c0463cd0c4113c":{
      "scriptId":"u25"},
    "2eb6b4859b8d47d688e1fe78b6e2e681":{
      "scriptId":"u26"},
    "465150bf6107491a93de0cc1b2f032ad":{
      "scriptId":"u27",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u28"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u29"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u30"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u31"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u32"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u33"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u34"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u35"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u36"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u37"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u38"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u39"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u40"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u41"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u42"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u43"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u44"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u45"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u46"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u47"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u48"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u49"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u50"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u51"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u52"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u53"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u54"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u55"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u56"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u57"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u58"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u59"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u60"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u61"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u62"}},
    "dfa53bc0d8f14f7b9feff7382dc808ca":{
      "scriptId":"u63"},
    "6348f140319243c0b684e3448cfeacf7":{
      "scriptId":"u64"}}});