$axure.loadCurrentPage({
  "url":"个人设置.html",
  "generationDate":new Date(1449315208945.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"135df0dfa53b4f0cad44be7bd7242e69",
    "type":"Axure:Page",
    "name":"个人设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d8f163a1dcd49e483860c57d5a23315",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e676675b25f493bbca2023209639a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"557ea4af475d4f91aed8c77cdd11bf71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":86},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f86f0a724a4db58bec227f00956431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":86},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9efb8080572e4bb981b1bb3bf4133341",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"b3d158faaf8e42e7ad83c9878a4cafa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":154},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9f8ff5253b54e72aa2a788bcec7a9de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":154},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"924829b04316413ca6df88db47664954",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":149.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a4bb610dbaab4a5b83c50a6d95a7fd91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":203},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d516713c6f440aaf535333d78c4382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":203},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a42eb8f7278b42b3b2d39d24c9740fd2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":203},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48951f5a3ccd4809af0231df247bcbf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":203},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0affe4fdb4754c298d640cc4dc567b6e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":203},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a640b656e2b1427fb14376403108ec7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":203},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"78b4e0fa563b410f8f1be93c31c1063a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":203},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"877920bf92924c6fbd0a1694daa0261b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":203},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"25c473e87ac04633b4c741a26a7900be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":254},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a61a74174574c4e899817821cf9ccce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":254},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df2457de3efc48a5a585cc16feb52b77",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":254},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"61fcef20ce1f4adea7f61172a90a15df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":334},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f84b64b35d74e1abe85c342776d855e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":334},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d46daaec258c420b80ec43fd5e303646",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":334},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b7d01970861c499697de210b60260c0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e33c47f3907d4f0fb2a685c4651929f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45a280eaa0004b5f932dd62639aaf74c",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":404},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"068576c3a96f4fc6ad4995340cc17964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":574},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c382e163aa24b02845f5fb1d1670b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":574},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1031d3811bb4248a9bea242d571be49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":624},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4536aefac033422087009ec30b00bace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":624},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb1f1e5ad1c4249bb4bdb8b23317882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":760},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1040cddbdd479cba7dd0b3a9b92fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":760},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/书签/u14.png"}},
{
          "id":"a99dda89953941988b8c2661cef70ca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":660},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0599153c4176478fb4e96e4093d7a3b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":660},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ef477aeaa114c00a63f9798b73032d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":640},
            "size":{
              "width":687,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fb00747f7ad4b4180dda036766a4a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":640},
                "size":{
                  "width":687,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人设置/u68.png"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2d8f163a1dcd49e483860c57d5a23315":{
      "scriptId":"u0"},
    "7e676675b25f493bbca2023209639a6a":{
      "scriptId":"u1"},
    "557ea4af475d4f91aed8c77cdd11bf71":{
      "scriptId":"u2"},
    "d0f86f0a724a4db58bec227f00956431":{
      "scriptId":"u3"},
    "9efb8080572e4bb981b1bb3bf4133341":{
      "scriptId":"u4",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u5"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u6"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u7"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u8"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u9"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u10"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u11"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u12"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u13"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u14"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u15"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u16"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u17"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u18"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u19"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u20"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u21"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u22"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u23"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u24"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u25"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u26"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u27"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u28"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u29"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u30"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u31"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u32"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u33"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u34"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u35"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u36"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u37"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u38"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u39"}},
    "b3d158faaf8e42e7ad83c9878a4cafa4":{
      "scriptId":"u40"},
    "a9f8ff5253b54e72aa2a788bcec7a9de":{
      "scriptId":"u41"},
    "924829b04316413ca6df88db47664954":{
      "scriptId":"u42"},
    "a4bb610dbaab4a5b83c50a6d95a7fd91":{
      "scriptId":"u43"},
    "59d516713c6f440aaf535333d78c4382":{
      "scriptId":"u44"},
    "a42eb8f7278b42b3b2d39d24c9740fd2":{
      "scriptId":"u45"},
    "48951f5a3ccd4809af0231df247bcbf0":{
      "scriptId":"u46"},
    "0affe4fdb4754c298d640cc4dc567b6e":{
      "scriptId":"u47"},
    "a640b656e2b1427fb14376403108ec7c":{
      "scriptId":"u48"},
    "78b4e0fa563b410f8f1be93c31c1063a":{
      "scriptId":"u49"},
    "877920bf92924c6fbd0a1694daa0261b":{
      "scriptId":"u50"},
    "25c473e87ac04633b4c741a26a7900be":{
      "scriptId":"u51"},
    "7a61a74174574c4e899817821cf9ccce":{
      "scriptId":"u52"},
    "df2457de3efc48a5a585cc16feb52b77":{
      "scriptId":"u53"},
    "61fcef20ce1f4adea7f61172a90a15df":{
      "scriptId":"u54"},
    "0f84b64b35d74e1abe85c342776d855e":{
      "scriptId":"u55"},
    "d46daaec258c420b80ec43fd5e303646":{
      "scriptId":"u56"},
    "b7d01970861c499697de210b60260c0c":{
      "scriptId":"u57"},
    "e33c47f3907d4f0fb2a685c4651929f9":{
      "scriptId":"u58"},
    "45a280eaa0004b5f932dd62639aaf74c":{
      "scriptId":"u59"},
    "068576c3a96f4fc6ad4995340cc17964":{
      "scriptId":"u60"},
    "1c382e163aa24b02845f5fb1d1670b5f":{
      "scriptId":"u61"},
    "f1031d3811bb4248a9bea242d571be49":{
      "scriptId":"u62"},
    "4536aefac033422087009ec30b00bace":{
      "scriptId":"u63"},
    "7bb1f1e5ad1c4249bb4bdb8b23317882":{
      "scriptId":"u64"},
    "9e1040cddbdd479cba7dd0b3a9b92fba":{
      "scriptId":"u65"},
    "a99dda89953941988b8c2661cef70ca8":{
      "scriptId":"u66"},
    "0599153c4176478fb4e96e4093d7a3b1":{
      "scriptId":"u67"},
    "2ef477aeaa114c00a63f9798b73032d7":{
      "scriptId":"u68"},
    "1fb00747f7ad4b4180dda036766a4a15":{
      "scriptId":"u69"}}});