$axure.loadCurrentPage({
  "url":"博客.html",
  "generationDate":new Date(1449315207719.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"f9b7ad270c614ced938e198f81d919af",
    "type":"Axure:Page",
    "name":"博客",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"128baef176444a39827b362adf74134c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89bea20f7bb14dd5867f91a11d31bbac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"06281ea834e54b6b8c31c3c65d075a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Adobe 楷体 Std R', 'Adobe 楷体 Std'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":49,
              "y":0},
            "size":{
              "width":93,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5164660602b4093a4c82e2974c2c139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 楷体 Std R', 'Adobe 楷体 Std'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":0},
                "size":{
                  "width":93,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"790a73a022a84740befb517cfbca79a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":423,
              "y":17},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"305e373b9a634185910fef597a18371c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":423,
                  "y":17},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16d855286c66466e895f0465d2d4d911",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":17},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7d88310f45400792d48095e4af40ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":17},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e875de35217f47ac98c3c7e9413c24ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":30,
              "y":74},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2c8b2e012884fa3a642a1aeb0d55a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":30,
                  "y":74},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46bef9600fbb4ea38ac521f4c9b46620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":74},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e651fff332b46eba188e02402613a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":74},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cabe5f4de49144509c050ff640cd73eb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "location":{
              "x":0,
              "y":103},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/问答社区/u10_line.png"}},
{
          "id":"314e626f19174dc189f62a0c4cf423f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":138},
            "size":{
              "width":587,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a609f75ea6454c15bc7d9b2c0b45ecea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":138},
                "size":{
                  "width":587,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/博客/u13.png"}},
{
          "id":"4539e94852274d8195289ad43e3090fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCFF},
            "location":{
              "x":85,
              "y":150.523345947266},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc609b1cbad4ebfa514778b291a040a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF},
                "location":{
                  "x":85,
                  "y":150.523345947266},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 分类文章 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"分类文章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/博客/u15.png"}},
{
          "id":"42486c779a884df8b24c79753b832c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":209},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069d1b7175e34cfa991a3ace71804836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":209},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb5e222998b74a00995693d7d4da9f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":600,
              "y":70},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f56cb51f50a14c558f05e9856ef7308f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":70},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 我要写文章 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"我要写文章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/书签/u14.png"}},
{
          "id":"49d4de7138634472885ada2804e45005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":845,
              "y":17},
            "size":{
              "width":155,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77d538adac14a36984113c4319babfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":845,
                  "y":17},
                "size":{
                  "width":155,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9a07e9882da45b097531c92f6ed1689",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":150.523345947266},
            "size":{
              "width":29,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27aff57e698043929031d040aa0934a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":150.523345947266},
                "size":{
                  "width":29,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/问答社区/u78.png"}},
{
          "id":"3421ab66832a4c25a977a54977254bd0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":142},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 文章详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"文章详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f9ef26955f7a48d8bcd643ea8904c61c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":399.5,
              "y":145},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set value of LabelState equal to &quot;文章&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"LabelState"},
{
                                "exprType":"stringLiteral",
                                "value":"文章",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"Open 标签 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"标签.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aafc5dc0aa414e0f8d52f6a3fa69225c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354.523345947266,
              "y":182.523345947266},
            "size":{
              "width":96,
              "height":10},
            "rotation":"45"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/添加书签/u63_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/博客/u27_line.png"}},
{
          "id":"446f95c41aac43128f45327fc6ceaa23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":370,
              "y":230},
            "size":{
              "width":350,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbc2cc85cd8e4ca8b7e32a499d1c79f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":230},
                "size":{
                  "width":350,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b86b7461d18448b2905bffc4225700c1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"5134abf58af04da6acbb19a52cbf5d1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":163.090728759766},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/博客/u66_line.png"}},
{
          "id":"1a08ffaaff3f464d8bacc79625011791",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":120},
            "size":{
              "width":300,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa96cca20fe046459b0197688245a6d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1060,
                  "y":120},
                "size":{
                  "width":300,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0674911ab82d403b85f1b71c0af35aae",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":113},
            "size":{
              "width":10,
              "height":1177}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/博客/u69_line.png"}},
{
          "id":"25d073bfb9fd4f25b51f5c9da37e535b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":742,
              "y":136},
            "size":{
              "width":98,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17450edc465f48c296380051fb7ce406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":742,
                  "y":136},
                "size":{
                  "width":98,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5555796981a742339e2d4dd750aba221",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":172},
            "size":{
              "width":29,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5d03af6e10245bdbfd4cbeb631e7e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":172},
                "size":{
                  "width":29,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/问答社区/u78.png"}},
{
          "id":"d032d141bda64b5999efc92fed675abe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":742,
              "y":244},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7c1f574a8ae4938b9ee28492b54bbae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":742,
                  "y":244},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61012b88cd67488dbd52bcf2b7537625",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":273},
            "size":{
              "width":238,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f50f7a7b59574a698fdd0ff32d0b2b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":742,
                  "y":273},
                "size":{
                  "width":238,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/问答社区/u82.png"}},
{
          "id":"c4eef5d291d34c2792744e1f2db00620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":742,
              "y":410},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ba9442924d54be59d6185e7bdf5d205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":742,
                  "y":410},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"676a9cde315b4b86b1352cc6c69047e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28.5,
              "y":260},
            "size":{
              "width":587,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93c87edac22748a58c6f382f81b458d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28.5,
                  "y":260},
                "size":{
                  "width":587,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/博客/u13.png"}},
{
          "id":"8b5c0a19aaa14349aadc4a8f64232da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":330},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b02ef7e5c264025861914fd456c4441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":330},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb8ae7dbb9e44537904b98561ec0e8bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCFF},
            "location":{
              "x":85,
              "y":270},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0347219ce9b4a20af0b4bfdaeb3fa12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF},
                "location":{
                  "x":85,
                  "y":270},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/博客/u84.png"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "128baef176444a39827b362adf74134c":{
      "scriptId":"u0"},
    "89bea20f7bb14dd5867f91a11d31bbac":{
      "scriptId":"u1"},
    "06281ea834e54b6b8c31c3c65d075a08":{
      "scriptId":"u2"},
    "d5164660602b4093a4c82e2974c2c139":{
      "scriptId":"u3"},
    "790a73a022a84740befb517cfbca79a8":{
      "scriptId":"u4"},
    "305e373b9a634185910fef597a18371c":{
      "scriptId":"u5"},
    "16d855286c66466e895f0465d2d4d911":{
      "scriptId":"u6"},
    "dc7d88310f45400792d48095e4af40ef":{
      "scriptId":"u7"},
    "e875de35217f47ac98c3c7e9413c24ff":{
      "scriptId":"u8"},
    "e2c8b2e012884fa3a642a1aeb0d55a57":{
      "scriptId":"u9"},
    "46bef9600fbb4ea38ac521f4c9b46620":{
      "scriptId":"u10"},
    "4e651fff332b46eba188e02402613a4b":{
      "scriptId":"u11"},
    "cabe5f4de49144509c050ff640cd73eb":{
      "scriptId":"u12"},
    "314e626f19174dc189f62a0c4cf423f9":{
      "scriptId":"u13"},
    "a609f75ea6454c15bc7d9b2c0b45ecea":{
      "scriptId":"u14"},
    "4539e94852274d8195289ad43e3090fb":{
      "scriptId":"u15"},
    "8dc609b1cbad4ebfa514778b291a040a":{
      "scriptId":"u16"},
    "42486c779a884df8b24c79753b832c52":{
      "scriptId":"u17"},
    "069d1b7175e34cfa991a3ace71804836":{
      "scriptId":"u18"},
    "fb5e222998b74a00995693d7d4da9f25":{
      "scriptId":"u19"},
    "f56cb51f50a14c558f05e9856ef7308f":{
      "scriptId":"u20"},
    "49d4de7138634472885ada2804e45005":{
      "scriptId":"u21"},
    "d77d538adac14a36984113c4319babfa":{
      "scriptId":"u22"},
    "b9a07e9882da45b097531c92f6ed1689":{
      "scriptId":"u23"},
    "27aff57e698043929031d040aa0934a8":{
      "scriptId":"u24"},
    "3421ab66832a4c25a977a54977254bd0":{
      "scriptId":"u25"},
    "f9ef26955f7a48d8bcd643ea8904c61c":{
      "scriptId":"u26"},
    "aafc5dc0aa414e0f8d52f6a3fa69225c":{
      "scriptId":"u27"},
    "446f95c41aac43128f45327fc6ceaa23":{
      "scriptId":"u28"},
    "cbc2cc85cd8e4ca8b7e32a499d1c79f2":{
      "scriptId":"u29"},
    "b86b7461d18448b2905bffc4225700c1":{
      "scriptId":"u30",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u31"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u32"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u33"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u34"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u35"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u36"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u37"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u38"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u39"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u40"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u41"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u42"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u43"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u44"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u45"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u46"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u47"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u48"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u49"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u50"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u51"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u52"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u53"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u54"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u55"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u56"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u57"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u58"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u59"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u60"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u61"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u62"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u63"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u64"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u65"}},
    "5134abf58af04da6acbb19a52cbf5d1c":{
      "scriptId":"u66"},
    "1a08ffaaff3f464d8bacc79625011791":{
      "scriptId":"u67"},
    "fa96cca20fe046459b0197688245a6d1":{
      "scriptId":"u68"},
    "0674911ab82d403b85f1b71c0af35aae":{
      "scriptId":"u69"},
    "25d073bfb9fd4f25b51f5c9da37e535b":{
      "scriptId":"u70"},
    "17450edc465f48c296380051fb7ce406":{
      "scriptId":"u71"},
    "5555796981a742339e2d4dd750aba221":{
      "scriptId":"u72"},
    "d5d03af6e10245bdbfd4cbeb631e7e3a":{
      "scriptId":"u73"},
    "d032d141bda64b5999efc92fed675abe":{
      "scriptId":"u74"},
    "f7c1f574a8ae4938b9ee28492b54bbae":{
      "scriptId":"u75"},
    "61012b88cd67488dbd52bcf2b7537625":{
      "scriptId":"u76"},
    "f50f7a7b59574a698fdd0ff32d0b2b26":{
      "scriptId":"u77"},
    "c4eef5d291d34c2792744e1f2db00620":{
      "scriptId":"u78"},
    "0ba9442924d54be59d6185e7bdf5d205":{
      "scriptId":"u79"},
    "676a9cde315b4b86b1352cc6c69047e1":{
      "scriptId":"u80"},
    "93c87edac22748a58c6f382f81b458d2":{
      "scriptId":"u81"},
    "8b5c0a19aaa14349aadc4a8f64232da3":{
      "scriptId":"u82"},
    "3b02ef7e5c264025861914fd456c4441":{
      "scriptId":"u83"},
    "bb8ae7dbb9e44537904b98561ec0e8bf":{
      "scriptId":"u84"},
    "d0347219ce9b4a20af0b4bfdaeb3fa12":{
      "scriptId":"u85"}}});