$axure.loadCurrentPage({
  "url":"他人主页.html",
  "generationDate":new Date(1449315209159.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"0947cc4d60c7483ba417939fb935c86c",
    "type":"Axure:Page",
    "name":"他人主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cee8271ccdc7454a8cac6382ccce75cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ef8af9bce6490ebc4079322e1808b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/d3中文网/u0.png"}},
{
          "id":"b01a7a367a97487e980faae0e3c325a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":90},
            "size":{
              "width":319,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62aac5cf782f43379021e300ae78a90f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":90},
                "size":{
                  "width":319,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的主页/u2.png"}},
{
          "id":"f8697110a3494a50ba3378fe67996470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":238},
            "size":{
              "width":319,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d86367df13894b4ebb3d6a47d8183ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":238},
                "size":{
                  "width":319,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/他人主页/u4.png"}},
{
          "id":"915d0026d079401a8edcb97fb89615ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":156},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166cb69511e4401b985a457a94284bef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":156},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f5180095df431ca058e572fb8071f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":256},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e9d27afc5348a092cfcc498dffa9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":256},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77d0369ab8834ebbb83f4cd462a0668e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":256},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1ec7c47dfc4d48ad65c9001a6ef688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":256},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d1fac8cfab741dfa83a5103b17269d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":290},
            "size":{
              "width":316,
              "height":332}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da703adb6a4e49908faa2378516a7b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":290},
                "size":{
                  "width":316,
                  "height":332}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/他人主页/u12.png"}},
{
          "id":"f7d7cc05c8f44f5d9e9759c71253904a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":104},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc4636cdf2247ac96f9b01e155fa169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":104},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebbbc64fd470431199a7ac1d92c323ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":130},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4633453121fe4daa9a320ff7e0c21c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":130},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ce3edccadd4479a6d1941e8f8e67d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":104},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8be854bb174b7fba19aa1921ae60c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":104},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/书签/u14.png"}},
{
          "id":"384726ea5bf8490d85655c4ebb865595",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":246},
            "size":{
              "width":83,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"484ca21aecb94f559a398bfb9aa5d0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":246},
                "size":{
                  "width":83,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的主页/u12.png"}},
{
          "id":"c632bf9528714c6e924dd4f1ac8d33db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":370,
              "y":265},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4dd66dd57e54ec198b1037dbed0229d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":265},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 他人主页 to 提问",
                      "panelsToStates":[{
                          "panelPath":["aa2ccfbbfe864765b8a3f093ea38ec9e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"615fd280e57e4a40800df0789a091a6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":437,
              "y":265},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4386a02208e24958a7f4bf28a39a6bca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":437,
                  "y":265},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 他人主页 to 回答",
                      "panelsToStates":[{
                          "panelPath":["aa2ccfbbfe864765b8a3f093ea38ec9e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec48c1f7ca4d41d69cdaa271629e825b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":504,
              "y":265},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcbd28c224d94af2b6eedff0e107b9b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":504,
                  "y":265},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 他人主页 to 文章",
                      "panelsToStates":[{
                          "panelPath":["aa2ccfbbfe864765b8a3f093ea38ec9e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21d741b1ed3a46cab7e0bdeddc86f9cb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a3904ffbda8c4012945e87a0ef705959"},
{
          "id":"c17bb8644b7a47d98b35c0ebeeadc760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":574,
              "y":265},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487f1cca149e49bc86ad29b62253f034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":574,
                  "y":265},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 他人主页 to 我的书签",
                      "panelsToStates":[{
                          "panelPath":["aa2ccfbbfe864765b8a3f093ea38ec9e"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"575c2656c5834e68ac9c04ae8976b971",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":259},
            "size":{
              "width":40,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/添加书签/u63_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/问答社区/u69_line.png"}},
{
          "id":"cc85138de7ba4e70b223c6b866b8ce79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":710,
              "y":253},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1bed9f341044a40bcd4e9704a1c5635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":253},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa2ccfbbfe864765b8a3f093ea38ec9e",
          "label":"他人主页",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":300},
            "size":{
              "width":632,
              "height":350}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d9169c457b504766a01649aa3ba27210",
              "label":"提问",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"38909d62fc4b45e1bc455c3348e4b3d1",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":10},
                    "size":{
                      "width":388,
                      "height":69}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"400bb8a221eb4c1ea2dcd367a11411b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":10},
                        "size":{
                          "width":388,
                          "height":69}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u9.png"}},
{
                  "id":"203b4f0e6db3491e978d05217281e6e8",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":19},
                    "size":{
                      "width":40,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab2e642f85db4452959f058ba8cf8b4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":19},
                        "size":{
                          "width":40,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/问答社区/u21.png"}}]},
{
              "id":"b8d427478e2a4b7a9e44809e287b8e92",
              "label":"回答",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5abf8840e3d5458dbacf256aee58d06e",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":14},
                    "size":{
                      "width":400,
                      "height":66}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4819ae44c55d41d4bf817b2cf04993cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":14},
                        "size":{
                          "width":400,
                          "height":66}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的主页/u37.png"}}]},
{
              "id":"0fe65b6797a74bac94d1ccd2b50de7ce",
              "label":"文章",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9f9cfefae1ec40b2940871d7a5c76a46",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":20},
                    "size":{
                      "width":587,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a867181fb24e4306adf6c85d19fb5180",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":20},
                        "size":{
                          "width":587,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u13.png"}},
{
                  "id":"279e759e8893474daed9aecb2faeaf95",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99CCFF},
                    "location":{
                      "x":70,
                      "y":30},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23422c47caaf4223856ed668e8a26d53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF99CCFF},
                        "location":{
                          "x":70,
                          "y":30},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/博客/u84.png"}},
{
                  "id":"1ccf1441c598428fb02b7243e2cff424",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11aab4dd63ed4cf1be7b09b4ac533542",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":90},
                        "size":{
                          "width":64,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"f256c6fcb5e74082a753f3538630ba3c",
              "label":"我的书签",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ed78a37797f74ce8be170f728b3f33a3",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":500,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"590f7a1a56ba4df2996fa9bda4183a52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":500,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u21.png"}},
{
                  "id":"7957e2f9d4c143269b11622db1a77e8f",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":49},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9f0473c98504dc49b92a71bec08673f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":49},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6d2e98b6c02543348db6ad2f51f167fe",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":21},
                    "size":{
                      "width":157,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"525121640056435bb70438f04f4a6d74",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":21},
                        "size":{
                          "width":157,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6a2c96df40b4c0bbe17a6846464b999",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":36},
                    "size":{
                      "width":31,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd108cd53e90431092bbc325b892a638",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":36},
                        "size":{
                          "width":31,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/标签/u27.png"}},
{
                  "id":"85756847ef644535b9040581dfae82fc",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":444,
                      "y":27},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23120626b2c74e878644ba2ef2644f32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":444,
                          "y":27},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"620ecd8368d449e68605e7083dc84b66",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":444,
                      "y":53},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72385e632e074edab6106211a84caa78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":444,
                          "y":53},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a52a0c63a39a40e8ae3a784cef8c6a4d",
                  "label":"",
                  "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250.5,
                      "y":27},
                    "size":{
                      "width":39,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d98ca2476e504e3ca4ac00a9e3e947f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aa2ccfbbfe864765b8a3f093ea38ec9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":250.5,
                          "y":27},
                        "size":{
                          "width":39,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 标签 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"标签.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/书签/u73.png"}}]}]},
{
          "id":"4501695fcde440d781420adec0530ee5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "location":{
              "x":349,
              "y":290},
            "size":{
              "width":651,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/他人主页/u96_line.png"}}]}},
  "masters":{
    "a3904ffbda8c4012945e87a0ef705959":{
      "packageId":"a3904ffbda8c4012945e87a0ef705959",
      "type":"Axure:Master",
      "name":"首页导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"44616af995e845f1b12910bcab2f1990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"291b58fb98914ce1990da13e3e902a90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u13.png"}},
{
            "id":"bfb6817c793e437cbbe0f3e50d0e9c91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":49,
                "y":0},
              "size":{
                "width":121,
                "height":56}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f01f195d6cd9459f83d9b11fe67a78e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":49,
                    "y":0},
                  "size":{
                    "width":121,
                    "height":56}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"195bab6751c04e48a050dc61f312dd7a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":450,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e52cbcb7179849038a8d863482d95c8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":450,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 书签 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"书签.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e2b18181afa41dea7b970e3776d0bb1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":303,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"369a4611d0944209908a7cf30ec264d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":303,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 问答社区 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"问答社区.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fd17db5efb0840d5b4b28332d1dda110",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":6},
              "size":{
                "width":140,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 首页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1d7974bcc66548bb96f0b4e9d1f4bb5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":373,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0838a2fad9e84a5eb43a6b4b165aded7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":373,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4ed7f8e9bd614de3bab6180a78ade11e",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":4.5},
              "size":{
                "width":66,
                "height":53}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 博客 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"博客.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Toggle 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"935a4606383d4e2db4244cb7c79baf5a",
            "label":"博客分类",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":357,
                "y":57},
              "size":{
                "width":76,
                "height":144},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 博客分类",
                        "objectsToFades":[{
                            "objectPath":["935a4606383d4e2db4244cb7c79baf5a"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"ab294b720a644d3093563383d4fd3402",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"36ef3ba8b5764875b7e7a7dfa6bd6176",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"30e9c39f070141488dc95bf8bc272816",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 分类文章 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"分类文章.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"683a6fd65b154ac6a319d617ffd16db1",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7397a7e8e4b240e7a19a6e2098a24e8f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"3e00bc9f682c40018260ad67c5bcd15c",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f0dc07ce30174ab1922926f8389f500b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}},
{
                    "id":"15d281e5a1d84071983bbada9b3e5fcb",
                    "label":"",
                    "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":110},
                      "size":{
                        "width":70,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e6d4c44b7e854f0da3969004ccc8612d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"935a4606383d4e2db4244cb7c79baf5a",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":110},
                          "size":{
                            "width":70,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u30.png"}}]}]},
{
            "id":"87cb31cd53774547b8bcca7c027133f3",
            "label":"个人中心",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":930,
                "y":57},
              "size":{
                "width":70,
                "height":120},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]},
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"2bf666a7f6f641f4806fb229ce9f08a7",
                "label":"选项",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"2064a68504ca4ce1b1f73b03b735a0b8",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fb6fda7f420344b697415a9a143d2319",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 消息中心 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"消息中心.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"61957a3d23ee4624adbaf8be3c776be5",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":40},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fbffe954904e06a054cb3c5f12a6bc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":40},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 个人设置 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人设置.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}},
{
                    "id":"f70712fc8a0646baa99e9cd731617c8c",
                    "label":"",
                    "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":80},
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"995b820a40024d93a348d18d98c94bcc",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"87cb31cd53774547b8bcca7c027133f3",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/d3中文网/u26.png"}}]}]},
{
            "id":"6075337590424a1183c2d0450ab03556",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":930.5,
                "y":7},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show 个人中心",
                        "objectsToFades":[{
                            "objectPath":["87cb31cd53774547b8bcca7c027133f3"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true},
{
            "id":"3b8e11502ac64b5892709c9a8e4d688e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":939.5,
                "y":14},
              "size":{
                "width":31,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1af2cab925a24f77be52199d419329b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":939.5,
                    "y":14},
                  "size":{
                    "width":31,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 我的主页 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"我的主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/d3中文网/u42.png"}},
{
            "id":"7224f608329f4e86ab2f00c212688643",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":14},
              "size":{
                "width":181,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d1226f4bad649d0985c0e1d3673f8ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":14},
                  "size":{
                    "width":181,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/d3中文网/u44.png"}},
{
            "id":"64654c6491964b68ba13c5c46edceef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":20},
              "size":{
                "width":37,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6933a822fa6d46509c82abb496c17fd7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":20},
                  "size":{
                    "width":37,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open D3实例 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"d3实例.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "cee8271ccdc7454a8cac6382ccce75cc":{
      "scriptId":"u0"},
    "e9ef8af9bce6490ebc4079322e1808b4":{
      "scriptId":"u1"},
    "b01a7a367a97487e980faae0e3c325a5":{
      "scriptId":"u2"},
    "62aac5cf782f43379021e300ae78a90f":{
      "scriptId":"u3"},
    "f8697110a3494a50ba3378fe67996470":{
      "scriptId":"u4"},
    "d86367df13894b4ebb3d6a47d8183ac5":{
      "scriptId":"u5"},
    "915d0026d079401a8edcb97fb89615ed":{
      "scriptId":"u6"},
    "166cb69511e4401b985a457a94284bef":{
      "scriptId":"u7"},
    "96f5180095df431ca058e572fb8071f1":{
      "scriptId":"u8"},
    "45e9d27afc5348a092cfcc498dffa9fd":{
      "scriptId":"u9"},
    "77d0369ab8834ebbb83f4cd462a0668e":{
      "scriptId":"u10"},
    "ae1ec7c47dfc4d48ad65c9001a6ef688":{
      "scriptId":"u11"},
    "8d1fac8cfab741dfa83a5103b17269d8":{
      "scriptId":"u12"},
    "da703adb6a4e49908faa2378516a7b8b":{
      "scriptId":"u13"},
    "f7d7cc05c8f44f5d9e9759c71253904a":{
      "scriptId":"u14"},
    "dfc4636cdf2247ac96f9b01e155fa169":{
      "scriptId":"u15"},
    "ebbbc64fd470431199a7ac1d92c323ec":{
      "scriptId":"u16"},
    "4633453121fe4daa9a320ff7e0c21c79":{
      "scriptId":"u17"},
    "40ce3edccadd4479a6d1941e8f8e67d5":{
      "scriptId":"u18"},
    "8d8be854bb174b7fba19aa1921ae60c3":{
      "scriptId":"u19"},
    "384726ea5bf8490d85655c4ebb865595":{
      "scriptId":"u20"},
    "484ca21aecb94f559a398bfb9aa5d0d0":{
      "scriptId":"u21"},
    "c632bf9528714c6e924dd4f1ac8d33db":{
      "scriptId":"u22"},
    "c4dd66dd57e54ec198b1037dbed0229d":{
      "scriptId":"u23"},
    "615fd280e57e4a40800df0789a091a6c":{
      "scriptId":"u24"},
    "4386a02208e24958a7f4bf28a39a6bca":{
      "scriptId":"u25"},
    "ec48c1f7ca4d41d69cdaa271629e825b":{
      "scriptId":"u26"},
    "dcbd28c224d94af2b6eedff0e107b9b4":{
      "scriptId":"u27"},
    "21d741b1ed3a46cab7e0bdeddc86f9cb":{
      "scriptId":"u28",
      "44616af995e845f1b12910bcab2f1990":{
        "scriptId":"u29"},
      "291b58fb98914ce1990da13e3e902a90":{
        "scriptId":"u30"},
      "bfb6817c793e437cbbe0f3e50d0e9c91":{
        "scriptId":"u31"},
      "f01f195d6cd9459f83d9b11fe67a78e9":{
        "scriptId":"u32"},
      "195bab6751c04e48a050dc61f312dd7a":{
        "scriptId":"u33"},
      "e52cbcb7179849038a8d863482d95c8f":{
        "scriptId":"u34"},
      "5e2b18181afa41dea7b970e3776d0bb1":{
        "scriptId":"u35"},
      "369a4611d0944209908a7cf30ec264d2":{
        "scriptId":"u36"},
      "fd17db5efb0840d5b4b28332d1dda110":{
        "scriptId":"u37"},
      "1d7974bcc66548bb96f0b4e9d1f4bb5d":{
        "scriptId":"u38"},
      "0838a2fad9e84a5eb43a6b4b165aded7":{
        "scriptId":"u39"},
      "4ed7f8e9bd614de3bab6180a78ade11e":{
        "scriptId":"u40"},
      "935a4606383d4e2db4244cb7c79baf5a":{
        "scriptId":"u41"},
      "36ef3ba8b5764875b7e7a7dfa6bd6176":{
        "scriptId":"u42"},
      "30e9c39f070141488dc95bf8bc272816":{
        "scriptId":"u43"},
      "683a6fd65b154ac6a319d617ffd16db1":{
        "scriptId":"u44"},
      "7397a7e8e4b240e7a19a6e2098a24e8f":{
        "scriptId":"u45"},
      "3e00bc9f682c40018260ad67c5bcd15c":{
        "scriptId":"u46"},
      "f0dc07ce30174ab1922926f8389f500b":{
        "scriptId":"u47"},
      "15d281e5a1d84071983bbada9b3e5fcb":{
        "scriptId":"u48"},
      "e6d4c44b7e854f0da3969004ccc8612d":{
        "scriptId":"u49"},
      "87cb31cd53774547b8bcca7c027133f3":{
        "scriptId":"u50"},
      "2064a68504ca4ce1b1f73b03b735a0b8":{
        "scriptId":"u51"},
      "fb6fda7f420344b697415a9a143d2319":{
        "scriptId":"u52"},
      "61957a3d23ee4624adbaf8be3c776be5":{
        "scriptId":"u53"},
      "d7fbffe954904e06a054cb3c5f12a6bc":{
        "scriptId":"u54"},
      "f70712fc8a0646baa99e9cd731617c8c":{
        "scriptId":"u55"},
      "995b820a40024d93a348d18d98c94bcc":{
        "scriptId":"u56"},
      "6075337590424a1183c2d0450ab03556":{
        "scriptId":"u57"},
      "3b8e11502ac64b5892709c9a8e4d688e":{
        "scriptId":"u58"},
      "1af2cab925a24f77be52199d419329b4":{
        "scriptId":"u59"},
      "7224f608329f4e86ab2f00c212688643":{
        "scriptId":"u60"},
      "3d1226f4bad649d0985c0e1d3673f8ba":{
        "scriptId":"u61"},
      "64654c6491964b68ba13c5c46edceef4":{
        "scriptId":"u62"},
      "6933a822fa6d46509c82abb496c17fd7":{
        "scriptId":"u63"}},
    "c17bb8644b7a47d98b35c0ebeeadc760":{
      "scriptId":"u64"},
    "487f1cca149e49bc86ad29b62253f034":{
      "scriptId":"u65"},
    "575c2656c5834e68ac9c04ae8976b971":{
      "scriptId":"u66"},
    "cc85138de7ba4e70b223c6b866b8ce79":{
      "scriptId":"u67"},
    "d1bed9f341044a40bcd4e9704a1c5635":{
      "scriptId":"u68"},
    "aa2ccfbbfe864765b8a3f093ea38ec9e":{
      "scriptId":"u69"},
    "38909d62fc4b45e1bc455c3348e4b3d1":{
      "scriptId":"u70"},
    "400bb8a221eb4c1ea2dcd367a11411b1":{
      "scriptId":"u71"},
    "203b4f0e6db3491e978d05217281e6e8":{
      "scriptId":"u72"},
    "ab2e642f85db4452959f058ba8cf8b4f":{
      "scriptId":"u73"},
    "5abf8840e3d5458dbacf256aee58d06e":{
      "scriptId":"u74"},
    "4819ae44c55d41d4bf817b2cf04993cb":{
      "scriptId":"u75"},
    "9f9cfefae1ec40b2940871d7a5c76a46":{
      "scriptId":"u76"},
    "a867181fb24e4306adf6c85d19fb5180":{
      "scriptId":"u77"},
    "279e759e8893474daed9aecb2faeaf95":{
      "scriptId":"u78"},
    "23422c47caaf4223856ed668e8a26d53":{
      "scriptId":"u79"},
    "1ccf1441c598428fb02b7243e2cff424":{
      "scriptId":"u80"},
    "11aab4dd63ed4cf1be7b09b4ac533542":{
      "scriptId":"u81"},
    "ed78a37797f74ce8be170f728b3f33a3":{
      "scriptId":"u82"},
    "590f7a1a56ba4df2996fa9bda4183a52":{
      "scriptId":"u83"},
    "7957e2f9d4c143269b11622db1a77e8f":{
      "scriptId":"u84"},
    "d9f0473c98504dc49b92a71bec08673f":{
      "scriptId":"u85"},
    "6d2e98b6c02543348db6ad2f51f167fe":{
      "scriptId":"u86"},
    "525121640056435bb70438f04f4a6d74":{
      "scriptId":"u87"},
    "c6a2c96df40b4c0bbe17a6846464b999":{
      "scriptId":"u88"},
    "bd108cd53e90431092bbc325b892a638":{
      "scriptId":"u89"},
    "85756847ef644535b9040581dfae82fc":{
      "scriptId":"u90"},
    "23120626b2c74e878644ba2ef2644f32":{
      "scriptId":"u91"},
    "620ecd8368d449e68605e7083dc84b66":{
      "scriptId":"u92"},
    "72385e632e074edab6106211a84caa78":{
      "scriptId":"u93"},
    "a52a0c63a39a40e8ae3a784cef8c6a4d":{
      "scriptId":"u94"},
    "d98ca2476e504e3ca4ac00a9e3e947f3":{
      "scriptId":"u95"},
    "4501695fcde440d781420adec0530ee5":{
      "scriptId":"u96"}}});