$axure.loadCurrentPage({
  "url":"开发周期及分工.html",
  "generationDate":new Date(1449315205629.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"LabelState"],
  "page":{
    "packageId":"109c2d11a4094ad9b6562eebd7d6b470",
    "type":"Axure:Page",
    "name":"开发周期及分工",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a62fbfa1b5d34f5fb0876c74392fcd9d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":80},
            "size":{
              "width":653,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc98682bb044476ea68ff44a6cfcaf24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0101eee8681b4b049647cedbe3679730",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"36e615eb652e44c592335fa7f62379f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb0b268174d844a89e4620b8c9d4f9b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"9fd2914ff8dd43928b62cfcc2c169caf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":0},
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3320cbecdb14905aa5a32d20aa701cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"52d63b0c47224c75b1b1d19c33cf4c82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"322619c9fd3043068cc160986cda56d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"312bfaf04f0648d39014bc4592905732",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":186,
                  "y":0},
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c498586bb1964496805663037f06f08f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":186,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"fa1d3e0c16b14db589e7ff35afe38adc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":186,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"955d33fb0e8b4f248a358dd38a040e9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":186,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"2fde9bf332094280afdccd7471889bd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":0},
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a69f5c5171334bfca7e9d6dfd2fbd181",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"6eb874c88114485393934ce1fa440e5c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ddf299dc64b407abb9f64d4fdb81d43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"6a50beb5704e4caba22ec86de9789d16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":465,
                  "y":0},
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24ec9c23a4dc4844be75334b8becf4f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":465,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"8bf7aff340c04f768cff9aecc5e7b1e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":465,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c798cec2c0c443789c056d389ec093a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":465,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"adc0ac8505fa41c9879d6a8d09c294c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":93,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f1444641e964032a52d03f413735a8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u1.png"}},
{
              "id":"1d5ed2b5dea64be58a9e24c3ed073774",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":27},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c84600ac8c04b7bbc2455e9860c7c8b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":27},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u15.png"}},
{
              "id":"e7c1e6765a8744428af9f526bed536ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":558,
                  "y":0},
                "size":{
                  "width":95,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e76c3bf9f23b4c639c51c8c86e28a968",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":558,
                      "y":0},
                    "size":{
                      "width":95,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u13.png"}},
{
              "id":"48a229045c784b86b5718b6a77d5e62e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":558,
                  "y":27},
                "size":{
                  "width":95,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f3a45140b404449a6836f83e06802a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":558,
                      "y":27},
                    "size":{
                      "width":95,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u27.png"}}]},
{
          "id":"03a2be9b61994639ba579ca34a3737a6",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":170},
            "size":{
              "width":395,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c30c03907148e6b98a879e53466beb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6a8b0d952754920b01c3422a584d79e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"37a5e210b0fc4d6fbb4250418b71e8cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abdb7243de3142f4949a1d93f8ccd0cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u46.png"}},
{
              "id":"7c0de3d032094032a643779fc36f787e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63ee1567979146fca1f01e67ccec5cee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"c33c9be4d8ee48d2a42595b53d9383d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb5693fcc8534b7a9204fe2230dda817",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u46.png"}},
{
              "id":"b2f398320be74c1bb01280d89c77b2d7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9001dfe7e5e48d693374d636d791228",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"5189f01576d44b1d83d6ab23bb1a7e64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3aecca6057334fee9a22bd0e4b9ad5aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u46.png"}},
{
              "id":"b4148e5f75d84e85b4540a8b51f166e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":95,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4f8d4e42d0245b6ae68076f28947d87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":95,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u36.png"}},
{
              "id":"577baf4c8136482ebad2198e2b52078b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":95,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"911eeac235054635848a12849896932a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":95,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u27.png"}},
{
              "id":"68730f70517a494da8d4d7d1930b332e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90e9fc0aec1047948e40cebc7c790180",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"e5a41c2f2a704a59b025fb2b31e68753",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e49d629a00b34c3a9f80d64084397543",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"90ea5dac23164e9aad5717066fb1d20c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"210d502d35c7455a92311b42e06c6a09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u30.png"}},
{
              "id":"0c4d9c318ce04826a8c238d2f5abc457",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":95,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eaf10ccbcd6f41b19cb14cac96230877",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":95,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u36.png"}}]},
{
          "id":"6d3f9e5b0c5a4abb8db3b4f8ffb4bcc5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":170},
            "size":{
              "width":100,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8723efc7e73e40fea3019fdbfabbb0b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f9283d9059346d2903a9a3e4fcd6453",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u55.png"}},
{
              "id":"122ac5e81a874e3699384838ddfe0420",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62bf066cff2f43d3bc1d66415239508b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":60}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发周期及分工/u57.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a62fbfa1b5d34f5fb0876c74392fcd9d":{
      "scriptId":"u0"},
    "fc98682bb044476ea68ff44a6cfcaf24":{
      "scriptId":"u1"},
    "0101eee8681b4b049647cedbe3679730":{
      "scriptId":"u2"},
    "9fd2914ff8dd43928b62cfcc2c169caf":{
      "scriptId":"u3"},
    "e3320cbecdb14905aa5a32d20aa701cb":{
      "scriptId":"u4"},
    "312bfaf04f0648d39014bc4592905732":{
      "scriptId":"u5"},
    "c498586bb1964496805663037f06f08f":{
      "scriptId":"u6"},
    "2fde9bf332094280afdccd7471889bd6":{
      "scriptId":"u7"},
    "a69f5c5171334bfca7e9d6dfd2fbd181":{
      "scriptId":"u8"},
    "adc0ac8505fa41c9879d6a8d09c294c0":{
      "scriptId":"u9"},
    "5f1444641e964032a52d03f413735a8d":{
      "scriptId":"u10"},
    "6a50beb5704e4caba22ec86de9789d16":{
      "scriptId":"u11"},
    "24ec9c23a4dc4844be75334b8becf4f7":{
      "scriptId":"u12"},
    "e7c1e6765a8744428af9f526bed536ef":{
      "scriptId":"u13"},
    "e76c3bf9f23b4c639c51c8c86e28a968":{
      "scriptId":"u14"},
    "36e615eb652e44c592335fa7f62379f9":{
      "scriptId":"u15"},
    "fb0b268174d844a89e4620b8c9d4f9b7":{
      "scriptId":"u16"},
    "52d63b0c47224c75b1b1d19c33cf4c82":{
      "scriptId":"u17"},
    "322619c9fd3043068cc160986cda56d0":{
      "scriptId":"u18"},
    "fa1d3e0c16b14db589e7ff35afe38adc":{
      "scriptId":"u19"},
    "955d33fb0e8b4f248a358dd38a040e9d":{
      "scriptId":"u20"},
    "6eb874c88114485393934ce1fa440e5c":{
      "scriptId":"u21"},
    "9ddf299dc64b407abb9f64d4fdb81d43":{
      "scriptId":"u22"},
    "1d5ed2b5dea64be58a9e24c3ed073774":{
      "scriptId":"u23"},
    "3c84600ac8c04b7bbc2455e9860c7c8b":{
      "scriptId":"u24"},
    "8bf7aff340c04f768cff9aecc5e7b1e1":{
      "scriptId":"u25"},
    "c798cec2c0c443789c056d389ec093a2":{
      "scriptId":"u26"},
    "48a229045c784b86b5718b6a77d5e62e":{
      "scriptId":"u27"},
    "5f3a45140b404449a6836f83e06802a4":{
      "scriptId":"u28"},
    "03a2be9b61994639ba579ca34a3737a6":{
      "scriptId":"u29"},
    "68730f70517a494da8d4d7d1930b332e":{
      "scriptId":"u30"},
    "90e9fc0aec1047948e40cebc7c790180":{
      "scriptId":"u31"},
    "e5a41c2f2a704a59b025fb2b31e68753":{
      "scriptId":"u32"},
    "e49d629a00b34c3a9f80d64084397543":{
      "scriptId":"u33"},
    "90ea5dac23164e9aad5717066fb1d20c":{
      "scriptId":"u34"},
    "210d502d35c7455a92311b42e06c6a09":{
      "scriptId":"u35"},
    "0c4d9c318ce04826a8c238d2f5abc457":{
      "scriptId":"u36"},
    "eaf10ccbcd6f41b19cb14cac96230877":{
      "scriptId":"u37"},
    "f0c30c03907148e6b98a879e53466beb":{
      "scriptId":"u38"},
    "b6a8b0d952754920b01c3422a584d79e":{
      "scriptId":"u39"},
    "7c0de3d032094032a643779fc36f787e":{
      "scriptId":"u40"},
    "63ee1567979146fca1f01e67ccec5cee":{
      "scriptId":"u41"},
    "b2f398320be74c1bb01280d89c77b2d7":{
      "scriptId":"u42"},
    "c9001dfe7e5e48d693374d636d791228":{
      "scriptId":"u43"},
    "b4148e5f75d84e85b4540a8b51f166e2":{
      "scriptId":"u44"},
    "e4f8d4e42d0245b6ae68076f28947d87":{
      "scriptId":"u45"},
    "37a5e210b0fc4d6fbb4250418b71e8cb":{
      "scriptId":"u46"},
    "abdb7243de3142f4949a1d93f8ccd0cc":{
      "scriptId":"u47"},
    "c33c9be4d8ee48d2a42595b53d9383d2":{
      "scriptId":"u48"},
    "eb5693fcc8534b7a9204fe2230dda817":{
      "scriptId":"u49"},
    "5189f01576d44b1d83d6ab23bb1a7e64":{
      "scriptId":"u50"},
    "3aecca6057334fee9a22bd0e4b9ad5aa":{
      "scriptId":"u51"},
    "577baf4c8136482ebad2198e2b52078b":{
      "scriptId":"u52"},
    "911eeac235054635848a12849896932a":{
      "scriptId":"u53"},
    "6d3f9e5b0c5a4abb8db3b4f8ffb4bcc5":{
      "scriptId":"u54"},
    "8723efc7e73e40fea3019fdbfabbb0b6":{
      "scriptId":"u55"},
    "0f9283d9059346d2903a9a3e4fcd6453":{
      "scriptId":"u56"},
    "122ac5e81a874e3699384838ddfe0420":{
      "scriptId":"u57"},
    "62bf066cff2f43d3bc1d66415239508b":{
      "scriptId":"u58"}}});